// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElFormItemExtends: typeof import('./src/components/form/form-item/extends/el-form-item-extends.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    LyColorPicker: typeof import('./src/components/special/ly-color-picker.vue')['default']
    LyDivider: typeof import('./src/components/special/ly-divider.vue')['default']
    LyForm: typeof import('./src/components/form/form/ly-form.vue')['default']
    LyFormItem: typeof import('./src/components/form/form-item/ly-form-item.vue')['default']
    LyIcon: typeof import('./src/components/special/ly-icon.vue')['default']
    LyInput: typeof import('./src/components/form/form-item/ly-input.vue')['default']
    LyToggle: typeof import('./src/components/special/ly-toggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
